### ISSUE TITLE
 No module named 'anubis.utils'

### ISSUE THREAD

**Issue by xj90512** [jonluca/Anubis#10]
Installing collected packages: anubis-netsec
Successfully installed anubis-netsec-0.2.0

~# anubis
Traceback (most recent call last):
  File "/usr/local/bin/anubis", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/anubis/cli.py", line 78, in main
    import anubis.commands
  File "/usr/local/lib/python3.5/dist-packages/anubis/commands/__init__.py", line 1, in <module>
    from .target import *
  File "/usr/local/lib/python3.5/dist-packages/anubis/commands/target.py", line 26, in <module>
    from anubis.utils.ColorPrint import ColorPrint
ImportError: No module named 'anubis.utils'

**Comment by samvdkris** [comment]
I got this as well when trying to install it using `pip3 install anubis-netsec`. For me cloning the repo and running `pip3 install -e .` fixed it, you might want to try that.

**Comment by jonluca** [comment]
I'm able to reproduce this, and an update will be submitted soon. 

For now, install by cloning and using `pip3 install .`.

Thanks!

**Comment by jonluca** [comment]
@xj90512 Should be fixed in v0.3.0. Let me know if this works for you.

**Comment by xj90512** [comment]
@jonluca ths，it's work.
