### ISSUE TITLE
using a list of domains is not working

### ISSUE THREAD

**Issue by IspeakwithTuna** [jonluca/Anubis#75]
@jonluca

- [x] Check you are using Python 3.6
- [x] Make sure you are using pip3 (or any instance of pip associated with Python 3.x)

### Bug reports:

Make sure you include the following:

* Anubis Version = 1.0.3
* Python Version = 3.9
* Full stack trace if crash or installation error
`Error connecting to target! Make sure you spelled it correctly and it is a resolvable address
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\anubis.exe\__main__.py", line 7, in <module>
  File "C:\Python39\lib\site-packages\anubis\cli.py", line 127, in main
    command.run()
  File "C:\Python39\lib\site-packages\anubis\commands\target.py", line 68, in run
    self.init()
  File "C:\Python39\lib\site-packages\anubis\commands\target.py", line 64, in init
    raise e
  File "C:\Python39\lib\site-packages\anubis\commands\target.py", line 59, in init
    domain_str = socket.gethostbyname(host)
socket.gaierror: [Errno 11001] getaddrinfo failed`
* Machine details (OS, build number, distro, etc.) = Windows 10

Tried to enumerate a list of domains with Anubis in Powershell.
Tried both:
example.com
https://example.com

To confirm the issue I asked a friend and he gets the same error. So Im assuming its code or format of the list related not a missing dependency.

**Comment by jonluca** [comment]
Does it work with a single domain passed as `-t`?

I can't reproduce this. This error is saying that it's not able to connect to the host.

I'll remove the raise though, so at least if a domain doesn't resolve anymore it'll still search for history.
